// $Dragan Jovic  <$dj47@zips.uakron.edu>
//
// main.cpp: DO NOT EDIT THIS FILE

#include "AVL.hpp"

#include <iostream>
#include <vector>

int main() {
  AVL<int> avl;

  std::cout << "----------------------------------------------------" << std::endl;
  for (auto x : { 1, 2, 3, 4, 5, 6, 7 })
    avl.insert(x);
  std::cout << avl.serialize() << std::endl;
  std::cout << "----------------------------------------------------\n" << std::endl;

  avl.clear();

  std::cout << "----------------------------------------------------" << std::endl;
  for (auto x : { 30, 10, 50, 48, 20 })
    avl.insert(x);
  std::cout << avl.serialize() << std::endl;
  std::cout << "----------------------------------------------------\n" << std::endl;

  avl.clear();

  std::cout << "----------------------------------------------------" << std::endl;
  for (auto x : { 1, 2, 3, 4, 5, 6, 7 })
    avl.insert(x);
  for (auto x : { 4, 3 })
    avl.remove(x);
  std::cout << avl.serialize() << std::endl;
  std::cout << "----------------------------------------------------\n" << std::endl;

  avl.clear();

  std::cout << "----------------------------------------------------" << std::endl;
  for (auto x : { 10, 5, 15, 9, 8, 7, 6 })
    avl.insert(x);
  for (auto x : { 10, 9 })
    avl.remove(x);
  for (auto x : { 30, 10, 11, 12 })
    avl.insert(x);
  std::cout << avl.serialize() << std::endl;
  std::cout << "----------------------------------------------------\n" << std::endl;

  avl.clear();
}
